#!/usr/bin/env python3
"""Generate docs/catalog.md from local Pi config files."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

PACKAGE_PURPOSES = {
    "npm:pi-web-access": ("npm", "Web/search/fetch tooling and related skills."),
    "npm:pi-subagents": ("npm", "Subagent orchestration: single, parallel, chains, async, council execution substrate."),
    "npm:pi-ask-user": ("npm", "Structured blocking user questions via `ask_user`."),
    "npm:@yofriadi/pi-lsp": ("npm", "LSP integration."),
    "npm:@ujjwalgrover/pi-catppuccin": ("npm", "Catppuccin themes."),
    "npm:pi-intercom": ("npm", "Local session-to-session coordination."),
    "npm:@ff-labs/pi-fff": ("npm", "Fast file finding / grep tools."),
    "git:github.com/IgorWarzocha/pi-auto-reasoning-tool": ("https://github.com/IgorWarzocha/pi-auto-reasoning-tool", "Auto-reasoning Pi extension."),
}

OPTIONAL_PACKAGE_PURPOSES = {
    "git:github.com/davebcn87/pi-autoresearch": ("https://github.com/davebcn87/pi-autoresearch", "Autoresearch package discovered in local git cache. Review before enabling."),
    "git:github.com/samfoy/pi-lsp-extension": ("https://github.com/samfoy/pi-lsp-extension", "Alternate/experimental LSP extension discovered in local git cache. Review before enabling."),
}

EXTENSION_PURPOSES = {
    "council-tools.ts": "Council run browser, `Alt+O` overlay, `/council-runs`, `/council-open`, and async council artifact backfill.",
    "guard.ts": "Safety guardrails for risky shell/git commands and secret-decryption operations.",
    "prompt-audit.ts": "Prompt/token audit commands (`/prompt-audit`, `/prompt-audit-save`) for measuring system prompt, provider payload, and tool schema overhead.",
    "project-commands.ts": "Slash commands for project cockpit/planning workflows: `/project-status`, `/project-roadmap`, `/project-deepen`, `/project-chunk`, `/project-wrap`, and `/project-momentum`.",
    "pi-nopii.ts.disabled": "Disabled experimental local PII-filter extension; kept off by default.",
}

CE_REPO = "https://github.com/EveryInc/compound-engineering-plugin"


def frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(errors="ignore")
    if not text.startswith("---\n"):
        return {}
    end = text.find("\n---", 4)
    if end == -1:
        return {}
    result: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        result[key.strip()] = value.strip().strip('"\'')
    return result


def first_heading_or_description(path: Path) -> str:
    text = path.read_text(errors="ignore")
    fm = frontmatter(path)
    if fm.get("description"):
        return fm["description"]
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return ""


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_package_refs(path: Path) -> list[str]:
    refs: list[str] = []
    if not path.exists():
        return refs
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            refs.append(line)
    return refs


def table(rows: list[list[str]]) -> str:
    if not rows:
        return ""
    out = ["| " + " | ".join(rows[0]) + " |", "| " + " | ".join("---" for _ in rows[0]) + " |"]
    out.extend("| " + " | ".join(row) + " |" for row in rows[1:])
    return "\n".join(out)


def link(path: Path, label: str | None = None) -> str:
    r = rel(path)
    # docs/catalog.md lives one directory below repo root, so links to repo files
    # need to climb back up to remain valid on GitHub.
    return f"[`{label or r}`](../{r})"


def package_link(source: str) -> str:
    if source == "npm":
        return "npm package"
    if source.startswith("https://"):
        return f"<{source}>"
    return source


def generate() -> str:
    lines: list[str] = []
    lines.append("# Pi Config Catalog")
    lines.append("")
    lines.append("Generated by `scripts/update-catalog.py`. Edit source files or the script, then regenerate.")
    lines.append("")
    lines.append("This catalog is meant to make the stack easy to skim: what is installed, what local pieces exist, and what each is for.")
    lines.append("")

    # Packages
    package_rows = [["Package", "Source", "Purpose"]]
    for ref in read_package_refs(ROOT / "config/pi-packages.txt"):
        source, purpose = PACKAGE_PURPOSES.get(ref, ("", ""))
        package_rows.append([f"`{ref}`", package_link(source), purpose])
    lines.append("## Package Dependencies")
    lines.append("")
    lines.append("Installed from npm/git with `scripts/install-packages.sh`; not vendored into this repo.")
    lines.append("")
    lines.append(table(package_rows))
    lines.append("")

    optional_rows = [["Package", "Source", "Notes"]]
    for ref in read_package_refs(ROOT / "config/pi-packages.optional.txt"):
        source, purpose = OPTIONAL_PACKAGE_PURPOSES.get(ref, ("", ""))
        optional_rows.append([f"`{ref}`", package_link(source), purpose])
    lines.append("### Optional / discovered packages")
    lines.append("")
    lines.append(table(optional_rows))
    lines.append("")

    # Compound Engineering resources
    ce_agent_count = len(list((ROOT / "agent/agents").glob("ce-*.md")))
    ce_skill_count = len(list((ROOT / "agent/skills").glob("ce-*/SKILL.md")))
    lines.append("## Compound Engineering Resources")
    lines.append("")
    lines.append(
        f"This setup includes a local snapshot of **{ce_skill_count} skills** and **{ce_agent_count} agents** installed by the "
        f"[Compound Engineering plugin]({CE_REPO}). They are treated as upstream plugin resources, not custom pi-config items. "
        "See the official CE repository for the canonical source, docs, and update flow."
    )
    lines.append("")

    # Extensions
    ext_rows = [["Extension", "Purpose"]]
    for path in sorted((ROOT / "agent/extensions").glob("*.ts")) + sorted((ROOT / "agent/extensions").glob("*.disabled")):
        ext_rows.append([link(path, path.name), EXTENSION_PURPOSES.get(path.name, "")])
    lines.append("## Local Extensions")
    lines.append("")
    lines.append(table(ext_rows))
    lines.append("")

    # Agents
    agent_rows = [["Agent", "Purpose"]]
    for path in sorted((ROOT / "agent/agents").glob("*.md")):
        if path.name.startswith("ce-"):
            continue
        fm = frontmatter(path)
        name = fm.get("name") or path.stem
        desc = fm.get("description") or first_heading_or_description(path)
        agent_rows.append([link(path, name), desc])
    lines.append("## Custom Local Agents")
    lines.append("")
    lines.append(table(agent_rows))
    lines.append("")

    # Shared cross-harness skills
    shared_rows = [["Skill", "Purpose"]]
    for path in sorted((ROOT / "shared-skills").glob("*/SKILL.md")):
        fm = frontmatter(path)
        name = fm.get("name") or path.parent.name
        desc = fm.get("description") or first_heading_or_description(path)
        shared_rows.append([link(path, name), desc])
    lines.append("## Shared Cross-Harness Skills")
    lines.append("")
    lines.append("These are tracked here for visibility, but are intended to live in `~/.agents/skills` so Pi and other harnesses can auto-discover them from the common location.")
    lines.append("")
    lines.append(table(shared_rows))
    lines.append("")

    # Skills
    skill_rows = [["Skill", "Purpose"]]
    skill_paths = sorted((ROOT / "agent/skills").glob("*/SKILL.md"))
    for path in skill_paths:
        if path.parent.name.startswith("ce-") or path.parent.name == "lfg":
            continue
        fm = frontmatter(path)
        name = fm.get("name") or path.parent.name
        desc = fm.get("description") or first_heading_or_description(path)
        skill_rows.append([link(path, name), desc])
    lines.append("## Custom Local Skills")
    lines.append("")
    lines.append(table(skill_rows))
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    (ROOT / "docs/catalog.md").write_text(generate())


if __name__ == "__main__":
    main()
